server:
  port: 8281
  servlet:
    context-path: /customer

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.205.137.178:3306/big-eat-drink?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 1qaz@WSX
  mvc:
    pathmatch:
      # Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X + 使用的是PathPatternMatcher
      matching-strategy: ant_path_matcher

# mybatis配置
mybatis:
  # 映射xml的文件位置
  mapper-locations: classpath:mapper/*.xml
  # 实体类所在包，简化xml中resultMap中实体类的全类名写法
  type-aliases-package: com.demo.entity


logging:
  level:
    com:
      demo:
        mapper: debug